import { globalStyle, style } from '@vanilla-extract/css'

export const page = style({ maxWidth: 1180, margin: '0 auto', padding: '3rem 1.25rem 6rem' })
export const eyebrow = style({ color: 'var(--storefront-fg-muted)', fontSize: '.75rem', fontWeight: 700, letterSpacing: '.12em' })
export const title = style({ margin: '0 0 2rem', fontSize: 'clamp(2rem, 5vw, 3.5rem)', fontFamily: 'Georgia, serif' })
export const layout = style({ display: 'grid', gap: '2rem', '@media': { 'screen and (min-width: 850px)': { gridTemplateColumns: '1.6fr 1fr', alignItems: 'start' } } })
export const lines = style({ listStyle: 'none', padding: 0, margin: 0, borderTop: '1px solid var(--storefront-line)' })
export const line = style({ display: 'grid', gridTemplateColumns: '5rem 1fr auto', gap: '1rem', padding: '1.25rem 0', borderBottom: '1px solid var(--storefront-line)', alignItems: 'center' })
globalStyle(`${line} img`, { width: '5rem', height: '6rem', objectFit: 'cover', borderRadius: '.6rem' })
export const details = style({})
globalStyle(`${details} h2`, { margin: 0, fontSize: '1rem' })
globalStyle(`${details} p`, { margin: '.35rem 0 .75rem', color: 'var(--storefront-fg-muted)' })
export const quantity = style({ display: 'flex', alignItems: 'center', gap: '.7rem' })
globalStyle(`${quantity} button`, { minWidth: '2rem', minHeight: '2rem', border: '1px solid var(--storefront-line)', borderRadius: '.3rem', background: 'transparent', cursor: 'pointer' })
export const remove = style({ border: 0, color: 'var(--storefront-fg-muted)', background: 'transparent', textDecoration: 'underline', cursor: 'pointer' })
export const lineTotal = style({ alignSelf: 'start', paddingTop: '.25rem', fontSize: '.95rem' })
export const summary = style({ padding: '1.5rem', borderRadius: '1rem', background: '#f1ede4' })
globalStyle(`${summary} h2`, { marginTop: 0 })
globalStyle(`${summary} p`, { color: 'var(--storefront-fg-muted)', fontSize: '.9rem' })
globalStyle(`${summary} small`, { display: 'block', marginTop: '.75rem', textAlign: 'center', color: 'var(--storefront-fg-muted)' })
export const total = style({ display: 'flex', justifyContent: 'space-between', padding: '1rem 0', borderTop: '1px solid var(--storefront-line)' })
export const button = style({ display: 'block', width: '100%', padding: '1rem 1.2rem', border: 0, borderRadius: '999px', background: 'var(--storefront-fg)', color: 'white', font: 'inherit', fontWeight: 700, textAlign: 'center', textDecoration: 'none', cursor: 'pointer', ':disabled': { opacity: .6, cursor: 'wait' } })
export const error = style({ color: '#a32828' })
export const empty = style({ padding: '2rem', borderRadius: '1rem', background: '#f1ede4', textAlign: 'center' })
globalStyle(`${empty} p`, { marginBottom: '1.5rem' })
